:Author: matthewtaylor
:Email: {AuthorEmail}
:Date: 23/01/2019
:Revision: version#
:License: Public Domain

= Project: {Project}

...

== Step 1: Installation

1. 
2. 
3. 

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 carpark-barrier-control-master  => Arduino sketch folder
  ├── sketch.ino                 => main Arduino file
  ├── schematics.png             => (optional) an image of the required schematics
  ├── layout.png                 => (optional) an image of the layout
  └── ReadMe.adoc                => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact matthewtaylor https://id.arduino.cc/matthewtaylor

=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
